name: 'argocd-promote'
description: 'image tag promotion action for TTL EU k8s services'
inputs:
  service:
    description: 'Name of the service'
    required: true
  environment:
    description: 'environment to target'
    required: true
    default: 'development'
  fromenv:
    description: 'environment to fetch image tag'
    required: false
  image_tag:
    description: 'image tag to update in the values.yaml'
    required: false
  access_token:
    description: 'github pat to commit to values repo'
    required: false
  branch:
    description: 'github pat to commit to values repo'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --service
    - ${{ inputs.service }}
    - --environment
    - ${{ inputs.environment }}
    - --from-env
    - ${{ inputs.fromenv }}
    - --image-tag
    - ${{ inputs.image_tag }}
    - --token
    - ${{ inputs.access_token }}
    - --branch
    - ${{ inputs.branch }}
