name: 'argocd-promote'
description: 'image tag promotion action for TTL EU k8s services'
inputs:
  service:
    description: 'Name of the service'
    required: true
  environment:
    description: 'environment to target'
    required: true
    default: 'development'
  fromenv:
    description: 'environment to fetch image tag'
    required: false
  image_tag:
    description: 'image tag to update in the values.yaml'
    required: false
  access_token:
    description: 'github pat to commit to values repo'
    required: true
  branch:
    description: 'github pat to commit to values repo'
    required: false
    default: 'main'
  createpr:
     description: 'flag to create PR instead of pushing to branch directly'
     required: false
     default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --service
    - ${{ inputs.service }}
    - --environment
    - ${{ inputs.environment }}
    - --token
    - ${{ inputs.access_token }}
