version: 1
formatters:
  json:
    '()': logging_json.JSONFormatter
    fields:
      level_name: levelname
      thread_name: threadName
      process_name: processName
      function_name: funcName
      file_name: filename
      line_no: lineno
handlers:
  standard_output:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
loggers:
  gitops:
    level: INFO
root:
  level: INFO
  handlers: [standard_output]
